sudo: required
services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t grumpywolf7/docker-react .

script: 
    - docker run -e CI=true grumpywolf7/docker-react npm run test
        
language: generic

deploy: 
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-671868619117"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY