sudo: required
services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t grumpywolf7/docker-react .

script: 
    - docker run -e CI=true grumpywolf7/docker-react npm run test
        
language: generic